version: "3"

services:
    client:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./docs:/usr/share/nginx/html